src_data = './data/clean/data/wikipedia_en_ne_si_test_sets/wikipedia.dev.ne-en.en'
tgt_data = './data/clean/data/wikipedia_en_ne_si_test_sets/wikipedia.dev.ne-en.ne'
src_lang = 'en'
tgt_lang = 'ne'
score_dir = './data/processed/tmp/'
